// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIPsaWXPXqwJDe7O76vgc9RMqKRvLZCzA',
    appId: '1:318804982348:web:fe6da2984e4e11e33052e9',
    messagingSenderId: '318804982348',
    projectId: 'demo1-dcd93',
    authDomain: 'demo1-dcd93.firebaseapp.com',
    storageBucket: 'demo1-dcd93.appspot.com',
    measurementId: 'G-69HYGHRWL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALoUYy7B7iqGONg70MHQLizh-hsJS_J7Q',
    appId: '1:318804982348:android:e7fd6e4320533f5d3052e9',
    messagingSenderId: '318804982348',
    projectId: 'demo1-dcd93',
    storageBucket: 'demo1-dcd93.appspot.com',
  );
}
